//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UchebPrak.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Akademiki
    {
        public int Id { get; set; }
        public string FIO { get; set; }
        public Nullable<System.DateTime> Birthsday { get; set; }
        public string Specialization { get; set; }
        public Nullable<int> GodPrisvoenia { get; set; }
    }
}
