//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UchebPrak.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Examen_Student
    {
        public int Id { get; set; }
        public Nullable<int> Examen_Id { get; set; }
        public Nullable<int> Student_RegNomer { get; set; }
        public Nullable<int> Ocenka { get; set; }
    
        public virtual Examen Examen { get; set; }
        public virtual Student Student { get; set; }
    }
}
