//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UchebPrak.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Examen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Examen()
        {
            this.Examen_Student = new HashSet<Examen_Student>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> ExamenDate { get; set; }
        public Nullable<int> Disciplina_Kod { get; set; }
        public Nullable<int> Prepodovatel_TabNomer { get; set; }
        public string Auditoria { get; set; }
    
        public virtual Disciplina Disciplina { get; set; }
        public virtual Prepodavatel Prepodavatel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Examen_Student> Examen_Student { get; set; }
    }
}
