//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UchebPrak.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gimnazisty
    {
        public int id { get; set; }
        public string familia { get; set; }
        public string predmet { get; set; }
        public string shkola { get; set; }
        public Nullable<int> balli { get; set; }
    }
}
