//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UchebPrak.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zayavka
    {
        public int Id { get; set; }
        public string Specialnost_Nomer { get; set; }
        public Nullable<int> Disciplina_Kod { get; set; }
    
        public virtual Disciplina Disciplina { get; set; }
        public virtual Specialnost Specialnost { get; set; }
    }
}
